# Generated by Django 3.1.3 on 2021-04-04 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('PK_Cart', models.AutoField(db_column='PK_Cart', primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(db_column='totalPrice', decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма')),
                ('totalItems', models.PositiveIntegerField(db_column='totalItems', default=0, verbose_name='Количество товаров')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('PK_Category', models.AutoField(db_column='PK_Category', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('PK_Color', models.AutoField(db_column='PK_Color', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='colorName', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('PK_Customer', models.AutoField(db_column='PK_Customer', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=100, null=True, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, db_column='surname', max_length=100, null=True, verbose_name='Фамилия')),
                ('midname', models.CharField(blank=True, db_column='midname', max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('PK_Gender', models.AutoField(db_column='PK_Gender', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Гендер',
                'verbose_name_plural': 'Гендеры',
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('PK_MainCategory', models.AutoField(db_column='PK_MainCategory', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главные категории',
                'db_table': 'MainCategory',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('PK_Size', models.AutoField(db_column='PK_Size', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='sizeName', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Размер одежды',
                'verbose_name_plural': 'Размеры одежды',
                'db_table': 'Size',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('PK_SubCategory', models.AutoField(db_column='PK_SubCategory', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('PK_Order', models.AutoField(db_column='PK_Order', primary_key=True, serialize=False)),
                ('nameCustomer', models.CharField(db_column='nameCustomer', max_length=255, verbose_name='Имя')),
                ('phoneCustomer', models.CharField(db_column='phoneCustomer', max_length=100, verbose_name='Телефон')),
                ('emailCustomer', models.EmailField(db_column='emailCustomer', max_length=254, verbose_name='E-mail')),
                ('date', models.DateTimeField(db_column='date', verbose_name='Дата заказа')),
                ('PK_Cart', models.ForeignKey(blank=True, db_column='PK_Cart', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.cart', verbose_name='Корзина')),
                ('PK_Customer', models.ForeignKey(blank=True, db_column='PK_Customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='PK_Gender',
            field=models.ForeignKey(blank=True, db_column='PK_Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('PK_Clothes', models.AutoField(db_column='PK_Clothes', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('imagePath', models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('PK_Category', models.ForeignKey(db_column='PK_Category', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.category', verbose_name='Категория')),
                ('PK_Color', models.ForeignKey(db_column='PK_Color', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.color', verbose_name='Цвет')),
                ('PK_MainCategory', models.ForeignKey(db_column='PK_MainCategory', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.maincategory', verbose_name='Главная категория')),
                ('PK_Size', models.ForeignKey(db_column='PK_Size', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.size', verbose_name='Размер')),
                ('PK_SubCategory', models.ForeignKey(db_column='PK_SubCategory', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
                'db_table': 'Clothes',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='PK_MainCategory',
            field=models.ForeignKey(db_column='PK_MainCategory', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.maincategory', verbose_name='Главная категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='PK_SubCategory',
            field=models.ForeignKey(db_column='PK_SubCategory', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('PK_CartItem', models.AutoField(db_column='PK_CartItem', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('imagePath', models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='', verbose_name='Фото')),
                ('PK_Color', models.ForeignKey(db_column='PK_Color', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.color', verbose_name='Цвет')),
                ('PK_Size', models.ForeignKey(db_column='PK_Size', on_delete=django.db.models.deletion.DO_NOTHING, to='ClothingStoreApp.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар корзины',
                'verbose_name_plural': 'Товары корзины',
                'db_table': 'CartItem',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(db_column='items', to='ClothingStoreApp.CartItem', verbose_name='Товары'),
        ),
    ]
